# Generated by Django 4.2 on 2023-04-24 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('uploader_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2023, 4, 24, 9, 35, 23, 91197))),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gifs', models.ManyToManyField(to='polls.gif')),
            ],
        ),
    ]
