# Generated by Django 4.2 on 2023-04-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deadline_date',
            field=models.DateField(default='2020-12-12'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='date_completion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='details',
            field=models.CharField(max_length=200),
        ),
    ]
