# Generated by Django 4.2 on 2023-04-30 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_film_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 30, 11, 17, 21, 372575, tzinfo=datetime.timezone.utc)),
        ),
    ]
