# Generated by Django 4.2 on 2023-05-02 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_alter_film_available_in_countries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 2, 10, 18, 52, 889034, tzinfo=datetime.timezone.utc)),
        ),
    ]
