# Generated by Django 4.2 on 2023-05-02 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_alter_film_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 2, 10, 19, 9, 21501, tzinfo=datetime.timezone.utc)),
        ),
    ]
