# Generated by Django 4.2 on 2023-05-02 11:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_alter_film_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 2, 11, 54, 47, 720120, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('film', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='film', to='films.film')),
            ],
        ),
    ]
