# Generated by Django 4.2 on 2023-05-02 12:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_alter_film_release_date_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 2, 12, 45, 40, 259435, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='poster',
            name='film',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='films.film'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='image',
            field=models.URLField(),
        ),
    ]
