# Generated by Django 4.2 on 2023-05-03 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_alter_film_release_date_alter_poster_film_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='film',
        ),
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 3, 7, 29, 21, 675583, tzinfo=datetime.timezone.utc)),
        ),
    ]
