# Generated by Django 4.2 on 2023-05-03 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0012_rating_alter_film_release_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 3, 10, 3, 11, 364253, tzinfo=datetime.timezone.utc)),
        ),
    ]
