# Generated by Django 4.2 on 2023-05-03 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0014_alter_film_release_date_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 3, 11, 41, 20, 153046, tzinfo=datetime.timezone.utc)),
        ),
    ]
