# Generated by Django 4.2 on 2023-05-03 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0016_alter_film_release_date_alter_rating_film_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Comment',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 3, 13, 18, 39, 196750, tzinfo=datetime.timezone.utc)),
        ),
    ]
