# Generated by Django 4.2 on 2023-05-04 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0017_rename_comment_comment_comment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poster',
        ),
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 4, 7, 17, 1, 958978, tzinfo=datetime.timezone.utc)),
        ),
    ]
