# Generated by Django 4.2 on 2023-05-04 07:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0018_delete_poster_alter_film_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 4, 7, 19, 49, 822050, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='films.film')),
            ],
        ),
    ]
