# Generated by Django 4.2 on 2023-05-04 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0020_comment_user_alter_film_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 4, 8, 12, 47, 980874, tzinfo=datetime.timezone.utc)),
        ),
    ]
