# Generated by Django 4.2 on 2023-04-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20230427_1206'),
    ]

    operations = [
    ]
